"use client";
import {useEffect,useMemo,useState} from "react";
const brands=["旅人日和","小拾光接送","迷旅台灣","拾光漫遊－假日旅行"];
const platforms=["Facebook","Instagram","Threads","小紅書"];
const seed={Facebook:"溫暖實用",Instagram:"短句＋Hashtag",Threads:"聊天互動",小紅書:"生活感種草"};
export default function Home(){
 const[brand,setBrand]=useState(brands[0]),[topic,setTopic]=useState(""),[tab,setTab]=useState("home");
 const[selected,setSelected]=useState(platforms),[drafts,setDrafts]=useState([]);\n const[schedules,setSchedules]=useState([]),[scheduleDraft,setScheduleDraft]=useState(null);\n const[media,setMedia]=useState([]),[mediaName,setMediaName]=useState(""),[mediaNote,setMediaNote]=useState("");\n const[ready,setReady]=useState(false);\n useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("gd-push-data")||"{}");if(saved.brand)setBrand(saved.brand);if(Array.isArray(saved.drafts))setDrafts(saved.drafts);if(Array.isArray(saved.schedules))setSchedules(saved.schedules);if(Array.isArray(saved.media))setMedia(saved.media)}catch{}finally{setReady(true)}},[]);\n useEffect(()=>{if(!ready)return;localStorage.setItem("gd-push-data",JSON.stringify({brand,drafts,schedules,media}))},[ready,brand,drafts,schedules,media]);
 const toggle=x=>setSelected(v=>v.includes(x)?v.filter(i=>i!==x):[...v,x]);
 const create=()=>{if(!topic.trim())return;setDrafts(selected.map((p,i)=>({id:Date.now()+i,platform:p,brand,topic:topic.trim(),style:seed[p],status:"待確認"})));setTab("drafts")};
 const plan=d=>{const now=new Date();const local=new Date(now.getTime()-now.getTimezoneOffset()*60000).toISOString().slice(0,16);setScheduleDraft({...d,when:local});setTab("schedule")};\n const savePlan=()=>{if(!scheduleDraft?.when)return;setSchedules(v=>[...v.filter(x=>x.id!==scheduleDraft.id),{...scheduleDraft,status:"已排程"}]);setDrafts(v=>v.map(x=>x.id===scheduleDraft.id?{...x,status:"已排程"}:x));setScheduleDraft(null)};\n const addMedia=()=>{if(!mediaName.trim())return;setMedia(v=>[{id:Date.now(),name:mediaName.trim(),note:mediaNote.trim(),brand,created:new Date().toLocaleDateString("zh-TW")},...v]);setMediaName("");setMediaNote("")};\n const title=useMemo(()=>({drafts:"待發布",schedule:"排程中心",media:"素材庫",stats:"成效分析",settings:"設定"}[tab]||""),[tab]);
 return <main><header><div><b>GD PUSH</b><small>AI 社群推廣助手</small></div><span>🌼</span></header>
 <section className="brand"><label>目前品牌</label><select value={brand} onChange={e=>setBrand(e.target.value)}>{brands.map(x=><option key={x}>{x}</option>)}</select></section>
 {tab==="home"?<><section className="hero"><div className="meg">📣</div><h1>今天想推什麼？</h1><p>先選平台、輸入主題，再建立待發布內容。</p><textarea value={topic} onChange={e=>setTopic(e.target.value)} placeholder="例如：這週主推台中 → 桃園機場接送"/>
 <div className="chips">{platforms.map(x=><button className={selected.includes(x)?"on":""} onClick={()=>toggle(x)} key={x}>{selected.includes(x)?"✓ ":""}{x}</button>)}</div>
 <button className="primary" disabled={!topic.trim()||!selected.length} onClick={create}>✨ 建立推廣草稿</button></section>
 <section className="grid"><button onClick={()=>setTab("drafts")}>📝<b>待發布</b><small>{drafts.length} 則草稿</small></button><button onClick={()=>setTab("schedule")}>📅<b>排程中心</b><small>安排發布時間</small></button><button onClick={()=>setTab("media")}>🖼️<b>素材庫</b><small>圖片與內容</small></button><button onClick={()=>setTab("stats")}>📊<b>成效分析</b><small>追蹤推廣結果</small></button></section></>:
 <section className="panel"><button className="back" onClick={()=>setTab("home")}>‹ 返回首頁</button><div className="big">🌼</div><h2>{title}</h2>
 {tab==="drafts"?(drafts.length?drafts.map(d=><article key={d.id}><div className="row"><b>{d.platform}</b><em>{d.status}</em></div><span>{d.brand}・{d.style}</span><p>{d.topic}</p><div className="actions"><button onClick={()=>plan(d)}>設定排程</button><button onClick={()=>setDrafts(v=>v.filter(x=>x.id!==d.id))}>刪除</button></div></article>):<p className="empty">目前沒有草稿，回首頁建立第一則。</p> ):tab==="schedule"?<>{scheduleDraft&&<article className="scheduler"><b>設定發布時間</b><span>{scheduleDraft.brand}・{scheduleDraft.platform}</span><p>{scheduleDraft.topic}</p><input type="datetime-local" value={scheduleDraft.when} onChange={e=>setScheduleDraft({...scheduleDraft,when:e.target.value})}/><button className="primary" onClick={savePlan}>儲存排程</button></article>}{schedules.length?schedules.sort((a,b)=>a.when.localeCompare(b.when)).map(d=><article key={d.id}><div className="row"><b>{d.platform}</b><em>已排程</em></div><span>{d.brand}</span><p>{d.topic}</p><strong>🕒 {d.when.replace("T"," ")}</strong><div className="actions"><button onClick={()=>setScheduleDraft(d)}>修改時間</button><button onClick={()=>{setSchedules(v=>v.filter(x=>x.id!==d.id));setDrafts(v=>v.map(x=>x.id===d.id?{...x,status:"待確認"}:x))}}>取消排程</button></div></article>):!scheduleDraft&&<p className="empty">目前沒有排程，先到「待發布」選一則內容。</p>}</>:tab==="media"?<><article className="mediaForm"><b>新增素材</b><span>先建立圖片／影片素材資料，下一階段再接實際上傳。</span><input value={mediaName} onChange={e=>setMediaName(e.target.value)} placeholder="素材名稱，例如：機場接送 A4 圖"/><textarea value={mediaNote} onChange={e=>setMediaNote(e.target.value)} placeholder="備註、文案方向、圖片用途"/><button className="primary" disabled={!mediaName.trim()} onClick={addMedia}>＋ 加入素材庫</button></article>{media.length?media.map(m=><article key={m.id}><div className="row"><b>🖼️ {m.name}</b><em>{m.created}</em></div><span>{m.brand}</span>{m.note&&<p>{m.note}</p>}<div className="actions"><button onClick={()=>{setTopic(m.note||m.name);setTab("home")}}>拿去推廣</button><button onClick={()=>setMedia(v=>v.filter(x=>x.id!==m.id))}>刪除</button></div></article>):<p className="empty">素材庫目前是空的，先建立第一筆素材。</p>}</>:<p className="empty">功能入口已建立，下一階段再接實際服務。</p>}
 </section>}
 <nav><button onClick={()=>setTab("home")}>🏠<span>首頁</span></button><button onClick={()=>setTab("drafts")}>✍️<span>內容</span></button><button onClick={()=>setTab("schedule")}>📅<span>排程</span></button><button onClick={()=>setTab("stats")}>📈<span>成效</span></button><button onClick={()=>setTab("settings")}>⚙️<span>設定</span></button></nav></main>
}